### PR TITLE
make CRA work cross-platform

### PR DESCRIPTION
**Pull request by chicoxyzzy**
Make `PUBLIC_URL` environment variable work on all the platforms

### CODE REVIEW

**Comment by chicoxyzzy** [comment]
@lamiazar @wujekbizon can you either try to run the updated app from this branch or follow the instructions in the README.md? I don't have a Windows machine with me.

**Review by lamiazar — APPROVED** [review]

**Comment by lamiazar** [comment]
@chicoxyzzy I will test now

**Comment by lamiazar** [comment]
@chicoxyzzy I'm still getting the same error, I tested that on your branch `cross_platform_cra`

**Comment by chicoxyzzy** [comment]
@lamiazar can you try these two ways to run the app and test if any of these work?
1) `set PUBLIC_URL=./ && ssc build`
2) `set PUBLIC=./ && npm run build && ssc run`

**Comment by wujekbizon** [comment]
I tried everything and still got an error

**Comment by lamiazar** [comment]
The build failed when I run this (I'm getting the same error) --> `set PUBLIC_URL=./ && ssc build`
I'm getting this output for `set PUBLIC=./ && npm run build && ssc run`
```

C:\Users\lamia\socket-examples\advanced\create-react-app>set PUBLIC=./ && npm run build && ssc run

> create-react-app@0.1.0 build
> react-scripts build

Creating an optimized production build...
Compiled successfully.

File sizes after gzip:

  46.62 kB  build\static\js\main.1c40095e.js
  1.79 kB   build\static\js\787.62ea5e01.chunk.js
  541 B     build\static\css\main.073c9b0a.css

The project was built assuming it is hosted at ./ /.
You can control this with the homepage field in your package.json.

The build folder is ready to be deployed.

Find out more about deployment here:

  https://cra.link/deployment

• executable not found: C:\Users\lamia\socket-examples\advanced\create-react-app\dist\win\create-react-app-example-dev-v1.0.0\create-react-app-example-dev.exe 5ms
```

**Comment by chicoxyzzy** [comment]
Please pull latest changes and try `ssc build -r` again

**Comment by chicoxyzzy** [comment]
image
it works for me

**Comment by chicoxyzzy** [comment]
it even works for both first commit and last commit

**Comment by chicoxyzzy** [comment]
are you running it from PowerShell?

**Comment by lamiazar** [comment]
> are you running it from PowerShell?
no, from command prompt
I'll try with PowerShell now

**Comment by wujekbizon** [comment]
I'm sorry, but it still doesn't work for me, even when using PowerShell.

**Comment by lamiazar** [comment]
@wujekbizon did you try updating `ssc` version? @chicoxyzzy has build the app from the latest master.

**Comment by wujekbizon** [comment]
> did you try updating `ssc` version? @chicoxyzzy has build the app from the latest master.

yes , I'm on the latest one. Is it working for you?

**Comment by lamiazar** [comment]
> yes , I'm on the latest one. Is it working for you?
I'm updating `ssc` now, I have an old version

**Comment by chicoxyzzy** [comment]
@mribbons can you try `ssc build -r` for this branch and `advanced/create-react-app` example too?

**Comment by chicoxyzzy** [comment]
@mribbons can you try `ssc build -r` for this branch and `advanced/create-react-app` example too?

**Pull request merged**
